//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZySharp.Progress {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZySharp.Progress.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input type must be a numeric type..
        /// </summary>
        internal static string InputTypeMustBeNumeric {
            get {
                return ResourceManager.GetString("InputTypeMustBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The multi-step progress has not been started (current step is &apos;0&apos;)..
        /// </summary>
        internal static string MultiStepProgressNotStarted {
            get {
                return ResourceManager.GetString("MultiStepProgressNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The next progress handler is already set..
        /// </summary>
        internal static string NextHandlerAlreadySet {
            get {
                return ResourceManager.GetString("NextHandlerAlreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The next progress handler not set..
        /// </summary>
        internal static string NextHandlerNotSet {
            get {
                return ResourceManager.GetString("NextHandlerNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enums with duplicate values are not supported..
        /// </summary>
        internal static string NotSupportedEnumDuplicateValues {
            get {
                return ResourceManager.GetString("NotSupportedEnumDuplicateValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty enums are not supported..
        /// </summary>
        internal static string NotSupportedEnumEmpty {
            get {
                return ResourceManager.GetString("NotSupportedEnumEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags enums are not supported..
        /// </summary>
        internal static string NotSupportedEnumFlags {
            get {
                return ResourceManager.GetString("NotSupportedEnumFlags", resourceCulture);
            }
        }
    }
}
